### ISSUE TITLE
Recent searches alignment off 

### ISSUE THREAD

**Issue by carlfredl** [busbud/alpine-node#4]
![Screen Shot 2017-09-22 at 8:26 PM](http://marker.screenshots.prod.s3.amazonaws.com/e1c5ba9ac71d496bbc20e0526633ab26-1506111995332.png)
---
### More Info

**Source URL**: [https://www.busbud.com/](https://www.busbud.com/)

<table><tr><td><strong>Browser</strong></td><td>Chrome 60.0.3112.113</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1440</td></tr><tr><td><strong>Viewport Size</strong></td><td>1263 x 1408</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.11.6</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36</td></tr></table>

**Comment by fredbusbud** [comment]
@CarlFredlund this should be in https://github.com/busbud/public-website
